// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Api.Data;

#nullable disable

namespace StudentManagement.Api.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20220918114722_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudentManagement.Api.Entities.Student", b =>
                {
                    b.Property<int>("RollNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollNumber"), 1L, 1);

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("English")
                        .HasColumnType("int");

                    b.Property<int>("Maths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Science")
                        .HasColumnType("int");

                    b.Property<int>("Social")
                        .HasColumnType("int");

                    b.Property<int>("Tamil")
                        .HasColumnType("int");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.HasKey("RollNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            RollNumber = 1,
                            Class = "XI",
                            Dob = "11-09-1996",
                            English = 74,
                            Maths = 98,
                            Name = "Mugesh",
                            Science = 99,
                            Social = 85,
                            Tamil = 89,
                            TotalMarks = 445
                        },
                        new
                        {
                            RollNumber = 2,
                            Class = "XI",
                            Dob = "11-09-1996",
                            English = 74,
                            Maths = 98,
                            Name = "Prakash",
                            Science = 99,
                            Social = 85,
                            Tamil = 89,
                            TotalMarks = 445
                        },
                        new
                        {
                            RollNumber = 3,
                            Class = "XI",
                            Dob = "11-09-1996",
                            English = 74,
                            Maths = 98,
                            Name = "Sagar",
                            Science = 99,
                            Social = 85,
                            Tamil = 89,
                            TotalMarks = 445
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
