// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Api.Data;

#nullable disable

namespace StudentManagement.Api.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20220918190915_ChangeInTableData")]
    partial class ChangeInTableData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudentManagement.Api.Entities.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            RollNumber = "8A001",
                            Address = "Chidambaram",
                            Class = "VIII",
                            Dob = "11-09-2009",
                            Email = "adhi.madhan@gmail.com",
                            FathersName = "Madhan",
                            Name = "Adhi",
                            PhoneNumber = "9952744908"
                        },
                        new
                        {
                            RollNumber = "8A002",
                            Address = "Cuddalore",
                            Class = "VIII",
                            Dob = "05-09-2009",
                            Email = "balu.dhileep@gmail.com",
                            FathersName = "Dhileep",
                            Name = "Balu",
                            PhoneNumber = "9488940491"
                        },
                        new
                        {
                            RollNumber = "8A003",
                            Address = "Pondicherry",
                            Class = "VIII",
                            Dob = "17-12-2009",
                            Email = "chinthan.vikram@gmail.com",
                            FathersName = "Vikram",
                            Name = "Chinthan",
                            PhoneNumber = "8610681447"
                        },
                        new
                        {
                            RollNumber = "8A004",
                            Address = "Chidambaram",
                            Class = "VIII",
                            Dob = "17-11-2009",
                            Email = "dinesh.aravind@gmail.com",
                            FathersName = "Aravind",
                            Name = "Dinesh",
                            PhoneNumber = "9443877178"
                        },
                        new
                        {
                            RollNumber = "8A005",
                            Address = "Chidambaram",
                            Class = "VIII",
                            Dob = "17-02-2010",
                            Email = "ezhil.mohan@gmail.com",
                            FathersName = "Mohan",
                            Name = "Ezhil",
                            PhoneNumber = "9488046422"
                        });
                });

            modelBuilder.Entity("StudentManagement.Api.Entities.StudentMarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("English")
                        .HasColumnType("int");

                    b.Property<int>("Maths")
                        .HasColumnType("int");

                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Science")
                        .HasColumnType("int");

                    b.Property<int>("Social")
                        .HasColumnType("int");

                    b.Property<int>("Tamil")
                        .HasColumnType("int");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentMarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            English = 95,
                            Maths = 95,
                            RollNumber = "8A001",
                            Science = 95,
                            Social = 95,
                            Tamil = 95,
                            TotalMarks = 475
                        },
                        new
                        {
                            Id = 2,
                            English = 90,
                            Maths = 90,
                            RollNumber = "8A002",
                            Science = 90,
                            Social = 90,
                            Tamil = 90,
                            TotalMarks = 450
                        },
                        new
                        {
                            Id = 3,
                            English = 85,
                            Maths = 85,
                            RollNumber = "8A003",
                            Science = 85,
                            Social = 85,
                            Tamil = 85,
                            TotalMarks = 425
                        },
                        new
                        {
                            Id = 4,
                            English = 75,
                            Maths = 75,
                            RollNumber = "8A004",
                            Science = 75,
                            Social = 75,
                            Tamil = 75,
                            TotalMarks = 400
                        },
                        new
                        {
                            Id = 5,
                            English = 70,
                            Maths = 70,
                            RollNumber = "8A005",
                            Science = 70,
                            Social = 70,
                            Tamil = 70,
                            TotalMarks = 375
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
